name: Build Android

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  testing:
    name: Build APK

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Assemble Debug APK
        run: ./android/gradlew assembleGpsStaging

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-gps-staging
          path: android/app/build/outputs/apk/gps/staging/app-gps-staging.apk
