name: Test

on:
  push:
    branches:
      - develop
      - master
      - bte-release
      - gps-release
  pull_request:
    branches:
      - develop
      - master
      - bte-release
      - gps-release

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: node --version

      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - run: yarn --frozen-lockfile

      - run: yarn test
        env:
          CI: true

  unit-test-android:
    needs: unit-test
    runs-on: macOS-latest # macOS-latest is required, tests need HAXM emulator
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-
      - run: yarn --frozen-lockfile

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: ./gradlew :app:connectedGpsDebugAndroidTest :app:connectedBteDebugAndroidTest --no-daemon
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew :app:connectedGpsDebugAndroidTest :app:connectedBteDebugAndroidTest --no-daemon
          working-directory: ./android

  unit-test-ios:
    runs-on: macOS-latest
    needs: unit-test
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@master

      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Cache node_modules/
        uses: actions/cache@v1
        id: node_cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - name: Install Node Dependencies
        if: steps.node_cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Install bundler for ruby package management
        run: gem install bundler -v "$(grep -A 1 "BUNDLED WITH" ./Gemfile.lock | tail -n 1)"
        working-directory: ./ios

      - name: Cache ruby gems
        uses: actions/cache@v1
        id: ruby_cache
        with:
          path: ios/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/ios/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby Dependencies
        if: steps.ruby_cache.outputs.cache-hit != 'true'
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: ./ios

      - name: Install Cocoapods
        run: bundle exec pod install --repo-update
        working-directory: ./ios

      - name: Unit Test iOS and Upload Simulator Friendly .app Zip
        uses: maierj/fastlane-action@v1.4.0
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTH: ${{ secrets.MATCH_GIT_BASIC_AUTH }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          lane: 'gps_unit_test'
          subdirectory: 'ios'
          bundle-install-path: 'vendor/bundle'

      - uses: actions/upload-artifact@v1
        with:
          name: e2e-ios-bin
          path: ios/fastlane/test_output/Staging-iphonesimulator/COVIDSafePaths.app

      - uses: actions/upload-artifact@v1
        with:
          name: e2e-ios-zip
          path: ios/fastlane/test_output/build_products.zip

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: JUnit Report
          path: ios/fastlane/test_output/report.junit

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: HTML Report
          path: ios/fastlane/test_output/report.html

  e2e-iphone-se:
    runs-on: macOS-latest
    needs: unit-test-ios
    timeout-minutes: 15
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4.app
    steps:
      - uses: actions/checkout@master
      - name: Cache node_modules/
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox-setup

      - name: Install Node Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - run: brew tap wix/brew

      - run: brew install applesimutils

      # - run: xcrun simctl list devicetypes

      # - run: xcrun simctl list runtimes

      - run: xcrun simctl create "iPhone SE" com.apple.CoreSimulator.SimDeviceType.iPhone-SE com.apple.CoreSimulator.SimRuntime.iOS-13-4

      - run: xcrun simctl list

      - uses: actions/download-artifact@master
        with:
          name: e2e-ios-bin
          path: ios/fastlane/test_output/Staging-iphonesimulator/COVIDSafePaths.app

      - run: yarn test:e2e:iphone-se

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: iPhone SE screenshots
          path: e2e/artifacts
